// generated by production/build.py - do not edit
window.STORY = {
 "title": "THE FORECAST IS MEMORY",
 "scenes": {
  "s01_broadcast": {
   "act": 1,
   "clock": 28,
   "amb": "shortwave",
   "solo": true,
   "title": "Station 417",
   "grants": [
    "E01"
   ],
   "sets": {
    "heard_broadcast": true
   },
   "next": "s02_brief",
   "id": "s01_broadcast",
   "segments": [
    {
     "asset": "s01_broadcast__00",
     "fx": "shortwave",
     "lines": [
      {
       "spk": "meteo",
       "text": "Achtung. Achtung. Station four one seven."
      },
      {
       "spk": "meteo",
       "text": "Wind, south south west, four. Cloud, broken. Visibility, three. Pressure, one one four nine."
      },
      {
       "spk": "meteo",
       "text": "Repeat. Pressure, one one four nine. Message follows."
      },
      {
       "spk": "meteo",
       "text": "Two seven. Four one. Nine nine. Two seven. Four one. Nine nine."
      },
      {
       "spk": "meteo",
       "text": "The forecast is memory. Ends."
      }
     ]
    }
   ]
  },
  "s02_brief": {
   "act": 1,
   "clock": 28,
   "amb": "vault",
   "title": "Tempelhof, sub-level four",
   "next": "s03_iris_phrase",
   "id": "s02_brief",
   "segments": [
    {
     "asset": "s02_brief__00",
     "fx": "vault",
     "lines": [
      {
       "spk": "vogt",
       "text": "Examiner. You are connected. Anneke Vogt, federal archive liaison. I am going to be quick because the building has stopped being polite."
      },
      {
       "spk": "vogt",
       "text": "Forty minutes ago a shortwave receiver in this room recorded what you just heard. The identifier is Station four one seven. That station transmitted from the eastern sector between nineteen seventy-nine and nineteen eighty-nine, and then it stopped, and everyone who cared about it died or retired."
      },
      {
       "spk": "vogt",
       "text": "The receiver also triggered a continuity protocol nobody has been able to switch off. GLASSHOUSE. We are sealed until the next transmission window closes."
      },
      {
       "spk": "vogt",
       "text": "That window is twenty-eight minutes away. You are the examiner because you are the only person on this line who was not part of it. Please keep it that way."
      }
     ]
    }
   ]
  },
  "s03_iris_phrase": {
   "act": 1,
   "clock": 27,
   "amb": "workstation",
   "title": "A phrase from a card",
   "grants": [
    "E03"
   ],
   "sets": {
    "iris_intro": true
   },
   "next": "s04_roster",
   "id": "s03_iris_phrase",
   "segments": [
    {
     "asset": "s03_iris_phrase__00",
     "fx": "workstation",
     "lines": [
      {
       "spk": "iris",
       "text": "Play the last five seconds again."
      },
      {
       "spk": "vogt",
       "text": "Doctor Halloway, we have not finished the-"
      },
      {
       "spk": "iris",
       "text": "Play it again, please."
      }
     ]
    },
    {
     "asset": "s03_iris_phrase__01",
     "fx": "sw_quote",
     "lines": [
      {
       "spk": "meteo",
       "text": "The forecast is memory. Ends."
      }
     ]
    },
    {
     "asset": "s03_iris_phrase__02",
     "fx": "workstation",
     "lines": [
      {
       "spk": "iris",
       "text": "That is not a station phrase. That is my father's handwriting."
      },
      {
       "spk": "iris",
       "text": "He sent me a card every February until I was fourteen. Nineteen eighty-six. A cartoon sun with a scarf on. Inside, in block capitals, the forecast is memory. I was nine. I thought he was being clever."
      },
      {
       "spk": "vogt",
       "text": "Your father disappeared in nineteen eighty-three."
      },
      {
       "spk": "iris",
       "text": "Yes. He did. And the cards kept coming for eight years after that, and nobody in this building has ever once asked me who was posting them."
      }
     ]
    }
   ]
  },
  "s04_roster": {
   "act": 1,
   "clock": 26,
   "amb": "vault",
   "title": "Who is on the line",
   "hub": true,
   "id": "s04_roster",
   "segments": [
    {
     "asset": "s04_roster__00",
     "fx": "vault",
     "lines": [
      {
       "spk": "vogt",
       "text": "Four voices, Examiner, and I have no authority over any of them. Dame Rosalind Frayne, seventy-eight, Halloway's handler in eighty-three, patched in from Wiltshire and furious about it."
      },
      {
       "spk": "vogt",
       "text": "Gene Dorsey, eighty-one, American liaison to GLASSHOUSE, now a private consultant, which is a word that means he still has everything and owes nobody."
      },
      {
       "spk": "vogt",
       "text": "Ulrich Nagel, seventy-four, was a radio technician for the Ministry for State Security. He listened to us for eleven years. He is now, absurdly, a consultant to this archive."
      },
      {
       "spk": "vogt",
       "text": "And Doctor Halloway, who you have met, and who should not be on this call at all."
      },
      {
       "spk": "vogt",
       "text": "Twenty-six minutes. Choose."
      }
     ]
    }
   ],
   "choices": [
    {
     "label": "Take Frayne first - she was the last of us to speak to him.",
     "goto": "s05_frayne_intro",
     "tag": "intro",
     "once": true
    },
    {
     "label": "Take Dorsey first - he ran the joint side of GLASSHOUSE.",
     "goto": "s06_dorsey_intro",
     "tag": "intro",
     "once": true
    },
    {
     "label": "Take Nagel first - he was listening in 1983.",
     "goto": "s07_nagel_intro",
     "tag": "intro",
     "once": true
    },
    {
     "label": "Enough. Pull the 1983 tape.",
     "goto": "s09_tape83",
     "req": {
      "tag_count": [
       "intro",
       2
      ]
     }
    }
   ]
  },
  "s05_frayne_intro": {
   "act": 1,
   "clock": 25,
   "amb": "study",
   "title": "Dame Rosalind Frayne",
   "sets": {
    "met_frayne": true
   },
   "next": "s04_roster",
   "id": "s05_frayne_intro",
   "segments": [
    {
     "asset": "s05_frayne_intro__00",
     "fx": "study",
     "lines": [
      {
       "spk": "frayne",
       "text": "Before you begin. I have given four statements about Peter Halloway. In nineteen eighty-three, in eighty-four, in ninety-one when it became fashionable, and in two thousand and nine to a committee that had already written its findings. They do not differ. Neither will this one."
      },
      {
       "spk": "frayne",
       "text": "He was my officer. He was tired. Tiredness in that profession resembles a great many other things, and I am not required to have distinguished between them at the time."
      },
      {
       "spk": "frayne",
       "text": "As to tonight. Somebody has found a way to make a dead woman read the weather. That is a technical crime, not a historical one, and I would be grateful if you did not confuse the two."
      }
     ]
    }
   ]
  },
  "s06_dorsey_intro": {
   "act": 1,
   "clock": 25,
   "amb": "line",
   "title": "Gene Dorsey",
   "sets": {
    "met_dorsey": true
   },
   "next": "s04_roster",
   "id": "s06_dorsey_intro",
   "segments": [
    {
     "asset": "s06_dorsey_intro__00",
     "fx": "line",
     "lines": [
      {
       "spk": "dorsey",
       "text": "Examiner. Gene Dorsey. Before anybody makes me the villain of this, let me say the only useful thing I know. That signal should be off the air inside the hour, and I don't much care whose feelings that hurts."
      },
      {
       "spk": "dorsey",
       "text": "I knew Peter. I liked him, which I'm aware is not what you were told to expect. He was the best cipher man either service had and he was also, at the end, a man who had decided something and didn't tell anybody what."
      },
      {
       "spk": "dorsey",
       "text": "Now Iris is on this line, so I'll say the hard part gently. There is a version of tonight where we find out her father went across of his own free will and stayed there. I'd rather we didn't go looking for it in front of her."
      },
      {
       "spk": "iris",
       "text": "Say it at normal volume, Gene. You've been saying it for forty years."
      }
     ]
    }
   ]
  },
  "s07_nagel_intro": {
   "act": 1,
   "clock": 25,
   "amb": "apartment",
   "title": "Ulrich Nagel",
   "sets": {
    "met_nagel": true,
    "nagel_named_ilse": true
   },
   "next": "s04_roster",
   "id": "s07_nagel_intro",
   "segments": [
    {
     "asset": "s07_nagel_intro__00",
     "fx": "apartment",
     "lines": [
      {
       "spk": "nagel",
       "text": "So. You have all heard her, and now you are frightened, and you have called the old enemy to explain the noise."
      },
      {
       "spk": "nagel",
       "text": "I was Hauptabteilung three. Radio. Eleven years of listening to British officers say clever things on frequencies they believed were private. It was the happiest work of my life."
      },
      {
       "spk": "nagel",
       "text": "Station four one seven was ours. The voice was a woman who read a list into a microphone in a room in Adlershof. Ilse. She had a cold that winter and you can hear it in nineteen eighty-one."
      },
      {
       "spk": "vogt",
       "text": "Nobody has said that name tonight."
      },
      {
       "spk": "nagel",
       "text": "No. Nobody has said it since nineteen eighty-nine. That is rather my point, Frau Vogt. You have a station and no announcer, and you would all prefer to discuss the station."
      }
     ]
    }
   ]
  },
  "s09_tape83": {
   "act": 2,
   "clock": 23,
   "amb": "tape83",
   "solo": true,
   "title": "14 October 1983",
   "grants": [
    "E02"
   ],
   "sets": {
    "heard_1983": true
   },
   "next": "s10_hub_investigate",
   "id": "s09_tape83",
   "segments": [
    {
     "asset": "s09_tape83__00",
     "fx": "tape83",
     "lines": [
      {
       "spk": "halloway",
       "text": "Control, this is Weathervane. Signal check, one, two, three."
      },
      {
       "spk": "halloway",
       "text": "Wind, north north east, two. Cloud, overcast. Visibility, eight. Pressure, zero nine nine one."
      },
      {
       "spk": "halloway",
       "text": "Control, an administrative note while I have the channel. If this set is returned to stores without me, the fault is in the second stage and not the aerial. Somebody will blame the aerial. They always do."
      },
      {
       "spk": "halloway",
       "text": "I have been asked to confirm my assessment of the courier problem. I confirm nothing. My assessment was wrong. I would like that recorded in exactly those words."
      },
      {
       "spk": "halloway",
       "text": "Tell Rosalind the weather is worse than forecast. Tell her I said that. She'll know which part I mean."
      },
      {
       "spk": "halloway",
       "text": "Weathervane out."
      }
     ]
    }
   ]
  },
  "s10_hub_investigate": {
   "act": 2,
   "clock": 22,
   "amb": "vault",
   "title": "Twenty-two minutes",
   "hub": true,
   "id": "s10_hub_investigate",
   "segments": [
    {
     "asset": "s10_hub_investigate__00",
     "fx": "vault",
     "lines": [
      {
       "spk": "vogt",
       "text": "Twenty-two minutes. The evidence locker is open to you and so is the line. I would advise you to spend at least one of those minutes on the recording itself rather than on the people arguing about it."
      }
     ]
    }
   ],
   "choices": [
    {
     "label": "Frayne: 'My assessment was wrong.' What assessment?",
     "goto": "s11_frayne_iv",
     "tag": "iv",
     "once": true
    },
    {
     "label": "Dorsey: what was the courier problem?",
     "goto": "s13_dorsey_iv",
     "tag": "iv",
     "once": true
    },
    {
     "label": "Nagel: you were listening that night. What did you hear?",
     "goto": "s15_nagel_iv",
     "tag": "iv",
     "once": true
    },
    {
     "label": "Iris: the cards. All of them.",
     "goto": "s18_iris_cards",
     "tag": "iv",
     "once": true
    },
    {
     "label": "Pull the checkpoint recording.",
     "goto": "s17_checkpoint",
     "req": {
      "tag_count": [
       "iv",
       2
      ]
     }
    }
   ]
  },
  "s11_frayne_iv": {
   "act": 2,
   "clock": 21,
   "amb": "study",
   "title": "The assessment",
   "grants": [
    "E04"
   ],
   "sets": {
    "knows_kroll": true,
    "frayne_iv": true
   },
   "id": "s11_frayne_iv",
   "segments": [
    {
     "asset": "s11_frayne_iv__00",
     "fx": "study",
     "lines": [
      {
       "spk": "frayne",
       "text": "The courier problem. Yes. In the summer of eighty-three we lost four sources in eleven weeks. Not arrests. Not trials. They simply became people who had never existed."
      },
      {
       "spk": "frayne",
       "text": "Peter was our cipher security. He built a correlation. Every compromised source had been handled through one courier chain, and that chain belonged to a West German officer named Willi Kroll."
      },
      {
       "spk": "frayne",
       "text": "He was certain. I have never seen him certain about anything before or since. He asked to go across and confirm it in person, and I let him, and that is the sentence I have said to four committees."
      },
      {
       "spk": "frayne",
       "text": "Then, on the fourteenth, he told an open channel that his assessment was wrong, and forty hours later he was a defector. You may draw the obvious conclusion. Everyone else did."
      }
     ]
    }
   ],
   "choices": [
    {
     "label": "'You logged him unstable on the twelfth. Two days before.'",
     "goto": "s12_frayne_log",
     "tag": "press"
    },
    {
     "label": "Let it stand. Move on.",
     "goto": "s10_hub_investigate"
    }
   ]
  },
  "s12_frayne_log": {
   "act": 2,
   "clock": 20,
   "amb": "study",
   "title": "The twelfth of October",
   "grants": [
    "E12"
   ],
   "sets": {
    "frayne_confessed": true,
    "trust_frayne": 1
   },
   "next": "s10_hub_investigate",
   "id": "s12_frayne_log",
   "segments": [
    {
     "asset": "s12_frayne_log__00",
     "fx": "study",
     "lines": [
      {
       "spk": "frayne",
       "text": "I did."
      },
      {
       "spk": "iris",
       "text": "You logged my father unstable two days before he crossed, and then you signed the authorisation to send him."
      },
      {
       "spk": "frayne",
       "text": "The entry is dated the twelfth. It was written on the twenty-third."
      },
      {
       "spk": "vogt",
       "text": "That is nine days after he disappeared. Dame Rosalind, that is a falsified record."
      },
      {
       "spk": "frayne",
       "text": "It is. I have known that for forty-three years and I have never once lost sleep over it, which I imagine disappoints you."
      },
      {
       "spk": "frayne",
       "text": "Understand what a review does, Examiner. If Peter was well, then a well man walked into the eastern sector and did not come out, and a review opens. A review reads the source files. The source files have names in them. Living names, in nineteen eighty-three."
      },
      {
       "spk": "frayne",
       "text": "So I made him unwell on paper, and there was no review, and eleven people who are alive today stayed alive. I would do it again this evening. I would do it before dinner."
      }
     ]
    }
   ]
  },
  "s13_dorsey_iv": {
   "act": 2,
   "clock": 21,
   "amb": "line",
   "title": "Gene Dorsey on the courier problem",
   "sets": {
    "dorsey_iv": true,
    "dorsey_slip_nine": true
   },
   "id": "s13_dorsey_iv",
   "segments": [
    {
     "asset": "s13_dorsey_iv__00",
     "fx": "line",
     "lines": [
      {
       "spk": "dorsey",
       "text": "The courier problem is what we called it afterward, which tells you something about us. At the time we called it a run of bad luck, and then we called it a leak, and then we stopped calling it anything in writing."
      },
      {
       "spk": "dorsey",
       "text": "Peter went looking for a person. That was his mistake, and I say that with affection. He was a mathematician. He believed that if a thing has an effect, it has a cause, and the cause has a name and an address."
      },
      {
       "spk": "dorsey",
       "text": "Sometimes a network just gets old, Examiner. Sometimes nine people know a thing and one of them tells his wife. There isn't always a traitor. There's just a lot of daylight and not enough curtain."
      },
      {
       "spk": "iris",
       "text": "Nine people."
      },
      {
       "spk": "dorsey",
       "text": "Figure of speech, sweetheart."
      },
      {
       "spk": "iris",
       "text": "It's a very specific figure of speech. The GLASSHOUSE handling list had nine names on it. That number has been classified since before I could read."
      },
      {
       "spk": "dorsey",
       "text": "Then I guess I read it somewhere I shouldn't have. At my age that's most places."
      }
     ]
    }
   ],
   "choices": [
    {
     "label": "'You've never seen that list. You said so in 2009, under oath.'",
     "goto": "s14_dorsey_press",
     "req": {
      "flag": "dorsey_slip_nine"
     },
     "tag": "press"
    },
    {
     "label": "Note it and move on.",
     "goto": "s10_hub_investigate"
    }
   ]
  },
  "s14_dorsey_press": {
   "act": 2,
   "clock": 20,
   "amb": "line",
   "title": "Under oath",
   "sets": {
    "dorsey_pressed": true
   },
   "next": "s10_hub_investigate",
   "id": "s14_dorsey_press",
   "segments": [
    {
     "asset": "s14_dorsey_press__00",
     "fx": "line",
     "lines": [
      {
       "spk": "dorsey",
       "text": "I said I had never held it. Which is true. I have never held that document in my hands."
      },
      {
       "spk": "frayne",
       "text": "Oh, Gene."
      },
      {
       "spk": "dorsey",
       "text": "Rosalind, don't."
      },
      {
       "spk": "frayne",
       "text": "Forty-three years and he still parses like a man with counsel in the room. He was read the list. Aloud. That is how the Americans took delivery of things they wished to be able to deny."
      },
      {
       "spk": "dorsey",
       "text": "That is a procedure, not a crime."
      },
      {
       "spk": "frayne",
       "text": "It is a procedure that exists for exactly one purpose, and you have just described it to a review examiner on a recorded line. Do go on."
      }
     ]
    }
   ]
  },
  "s15_nagel_iv": {
   "act": 2,
   "clock": 21,
   "amb": "apartment",
   "title": "What Nagel heard",
   "grants": [
    "E07"
   ],
   "sets": {
    "nagel_iv": true,
    "nagel_slip_available": true
   },
   "id": "s15_nagel_iv",
   "segments": [
    {
     "asset": "s15_nagel_iv__00",
     "fx": "apartment",
     "lines": [
      {
       "spk": "nagel",
       "text": "The fourteenth. Yes. I was on shift. I have thought about that night more often than about my wedding, which my wife did not consider a compliment."
      },
      {
       "spk": "nagel",
       "text": "I will play you something. It is not in your archive. It is not in our archive either, because I did not put it there. Listen to the announcer, not the words."
      },
      {
       "spk": "nagel",
       "text": "Now. She says it wrong. Nobody ever noticed. Visibility-"
      }
     ]
    },
    {
     "asset": "s15_nagel_iv__01",
     "fx": "sw_quote",
     "lines": [
      {
       "spk": "meteo",
       "text": "Visibility, three. Pressure, zero four one seven."
      }
     ]
    },
    {
     "asset": "s15_nagel_iv__02",
     "fx": "apartment",
     "lines": [
      {
       "spk": "nagel",
       "text": "There. You hear it? The stress on the front of the word. No trained announcer does that. It is a seam. The word was cut from two different afternoons and joined in the middle."
      },
      {
       "spk": "nagel",
       "text": "That is what four one seven was. Not a woman reading the news. A library. She read lists, and we built sentences she never said."
      },
      {
       "spk": "iris",
       "text": "Who is we."
      },
      {
       "spk": "nagel",
       "text": "Young men with razor blades and a great deal of time. It was the most beautiful work in the service and they gave it to the ones who were no good at anything else."
      }
     ]
    }
   ],
   "choices": [
    {
     "label": "'You said the seam before the tape played it.'",
     "goto": "s16_nagel_rhythm",
     "sets": {
      "nagel_slip": true
     },
     "tag": "press",
     "note": "Only lands here; if missed, recoverable at the bench."
    },
    {
     "label": "Ask how he knows a genuine Halloway transmission.",
     "goto": "s16_nagel_rhythm",
     "tag": "ask"
    }
   ]
  },
  "s16_nagel_rhythm": {
   "act": 2,
   "clock": 20,
   "amb": "apartment",
   "title": "Three, two, five",
   "grants": [
    "E15"
   ],
   "sets": {
    "knows_rhythm": true,
    "trust_nagel": 1
   },
   "next": "s10_hub_investigate",
   "id": "s16_nagel_rhythm",
   "segments": [
    {
     "asset": "s16_nagel_rhythm__00",
     "fx": "apartment",
     "lines": [
      {
       "spk": "nagel",
       "text": "Ah. Now you are asking a real question."
      },
      {
       "spk": "nagel",
       "text": "Your Halloway was cleverer than all of us. He knew we could forge any voice, any word, any number. So he did not authenticate with sound. He authenticated with silence."
      },
      {
       "spk": "nagel",
       "text": "Between his phrases: three beats. Two beats. Five beats. Always. Never written, never spoken, never in any manual. A man breathing in a pattern."
      },
      {
       "spk": "iris",
       "text": "Three, two, five."
      },
      {
       "spk": "nagel",
       "text": "It means something to you."
      },
      {
       "spk": "iris",
       "text": "The third of February, nineteen seventy-five. It's my birthday. He authenticated himself with my birthday."
      },
      {
       "spk": "nagel",
       "text": "Then you may do something none of us could. You may listen to tonight, and you will know at once which parts of it are your father."
      }
     ]
    }
   ]
  },
  "s17_checkpoint": {
   "act": 2,
   "clock": 19,
   "amb": "checkpoint",
   "solo": false,
   "title": "Friedrichstrasse, 02:14",
   "grants": [
    "E05"
   ],
   "sets": {
    "heard_checkpoint": true
   },
   "next": "s18_kroll_letter",
   "id": "s17_checkpoint",
   "segments": [
    {
     "asset": "s17_checkpoint__00",
     "fx": "checkpoint",
     "lines": [
      {
       "spk": "vogt",
       "text": "This is border police tape, western side, two fourteen in the morning on the fifteenth. It has been in the public catalogue since two thousand and four and nobody has ever listened to it, because it is nine minutes of men shouting."
      }
     ]
    },
    {
     "asset": "s17_checkpoint__01",
     "fx": "far",
     "lines": [
      {
       "spk": "kroll",
       "text": "Nein - nein, I am expected, my name is on the list, look at the list-"
      }
     ]
    },
    {
     "asset": "s17_checkpoint__02",
     "fx": "near",
     "lines": [
      {
       "spk": "halloway",
       "text": "Willi. Willi, look at me. Put it down."
      }
     ]
    },
    {
     "asset": "s17_checkpoint__03",
     "fx": "far",
     "lines": [
      {
       "spk": "kroll",
       "text": "They have already written it, Peter. They have already written it and it is my name in it-"
      }
     ]
    },
    {
     "asset": "s17_checkpoint__04",
     "fx": "near",
     "lines": [
      {
       "spk": "halloway",
       "text": "I know. I know they have. Give me the envelope."
      }
     ]
    },
    {
     "asset": "s17_checkpoint__05",
     "fx": "checkpoint",
     "lines": [
      {
       "spk": "vogt",
       "text": "And then thirty seconds of vehicle noise, and then the tape ends because the officer's shift ended."
      },
      {
       "spk": "iris",
       "text": "Play the second voice again."
      },
      {
       "spk": "vogt",
       "text": "Doctor Halloway-"
      },
      {
       "spk": "iris",
       "text": "I know what my father sounds like when he is frightened, Frau Vogt. That is not it. He is not frightened on that tape. He is deciding."
      }
     ]
    }
   ]
  },
  "s18_kroll_letter": {
   "act": 2,
   "clock": 18,
   "amb": "tape83",
   "solo": true,
   "title": "Unsent",
   "grants": [
    "E06"
   ],
   "sets": {
    "knows_kroll_innocent": true,
    "knows_kroll_would_talk": true
   },
   "next": "s19_hub_cipher",
   "id": "s18_kroll_letter",
   "segments": [
    {
     "asset": "s18_kroll_letter__00",
     "fx": "none",
     "lines": [
      {
       "spk": "vogt",
       "text": "Kroll's effects were returned to his sister in nineteen eighty-four. She gave them to this archive in two thousand and eleven. This was in the lining of the case. It is a dictation cylinder. He never posted it."
      }
     ]
    },
    {
     "asset": "s18_kroll_letter__01",
     "fx": "tape83",
     "lines": [
      {
       "spk": "kroll",
       "text": "Ilse. If you are hearing this then it has happened the way I think it will happen."
      },
      {
       "spk": "kroll",
       "text": "For nine weeks my chain has been the only chain they examine. Every meeting, I am asked the same four questions in a different order. I am not being investigated. I am being prepared."
      },
      {
       "spk": "kroll",
       "text": "I have asked the Englishman for help. He is honest, which in this work means he is dangerous to be near. He believes it is me. I can hear it in how kindly he speaks."
      },
      {
       "spk": "kroll",
       "text": "If they take me I will not be brave. I want to write that down while it is still a thing I am choosing. I have names, Ilse. I have your name. And I am not brave."
      }
     ]
    }
   ]
  },
  "s18_iris_cards": {
   "act": 2,
   "clock": 20,
   "amb": "workstation",
   "title": "Eight years of cards",
   "sets": {
    "iris_cards": true,
    "trust_iris": 1
   },
   "next": "s10_hub_investigate",
   "id": "s18_iris_cards",
   "segments": [
    {
     "asset": "s18_iris_cards__00",
     "fx": "workstation",
     "lines": [
      {
       "spk": "iris",
       "text": "Nineteen eighty-four to nineteen ninety-one. Eight cards. Posted from eight different cities, none of them the one he was in."
      },
      {
       "spk": "iris",
       "text": "Each one has a weather phrase in block capitals. Wind backing westerly. Fog on the low ground. The forecast is memory. As a child I assumed it was a joke about English small talk."
      },
      {
       "spk": "iris",
       "text": "It is a substitution table. Eight cards, eight rows. He sent me the key to his own cipher one line a year, at an age when I could not possibly understand it, to an address the service did not know I lived at."
      },
      {
       "spk": "vogt",
       "text": "You have had this since when."
      },
      {
       "spk": "iris",
       "text": "I have had eight birthday cards since I was seven, Frau Vogt. I have had a decryption key since about eleven o'clock this morning."
      }
     ]
    }
   ]
  },
  "s19_hub_cipher": {
   "act": 3,
   "clock": 17,
   "amb": "vault",
   "title": "Seventeen minutes",
   "hub": true,
   "id": "s19_hub_cipher",
   "segments": [
    {
     "asset": "s19_hub_cipher__00",
     "fx": "vault",
     "lines": [
      {
       "spk": "vogt",
       "text": "Seventeen minutes. Doctor Halloway has the substitution table and the archive has everything else. Tell us what to do with the numbers."
      }
     ]
    }
   ],
   "choices": [
    {
     "label": "Treat the values as real weather. Check them against the record.",
     "goto": "s20_impossible",
     "tag": "cipher",
     "once": true
    },
    {
     "label": "Plot the wind bearings as a route across the city.",
     "goto": "s21_route",
     "tag": "cipher",
     "once": true
    },
    {
     "label": "Read the pressure values as archive indices.",
     "goto": "s22_index",
     "tag": "cipher",
     "once": true
    },
    {
     "label": "Compare tonight's silences against the three-two-five rhythm.",
     "goto": "s24_insert",
     "req": {
      "flag": "knows_rhythm"
     },
     "tag": "cipher",
     "once": true
    },
    {
     "label": "Iris: forget the sound. Measure the silences.",
     "goto": "s23b_rhythm_alt",
     "req": {
      "not_flag": "knows_rhythm"
     },
     "tag": "cipher",
     "once": true
    },
    {
     "label": "Enough decoding. Go to the archive boxes.",
     "goto": "s23_archive",
     "req": {
      "flag": "decoded_index"
     }
    }
   ]
  },
  "s20_impossible": {
   "act": 3,
   "clock": 16,
   "amb": "workstation",
   "title": "No such weather",
   "grants": [
    "E08"
   ],
   "sets": {
    "decoded_impossible": true
   },
   "next": "s19_hub_cipher",
   "id": "s20_impossible",
   "segments": [
    {
     "asset": "s20_impossible__00",
     "fx": "workstation",
     "lines": [
      {
       "spk": "iris",
       "text": "I ran tonight's values against the German weather service record and then against every record there is. Pressure one one four nine."
      },
      {
       "spk": "vogt",
       "text": "Is that high?"
      },
      {
       "spk": "iris",
       "text": "The highest barometric pressure ever measured on this planet is one zero eight three point eight, in Mongolia, in nineteen sixty-eight. One one four nine is not high. One one four nine is not weather."
      },
      {
       "spk": "iris",
       "text": "And it is not a mistake either, because he does it every time. Nineteen eighty-one, eighty-three, tonight. Always one value that cannot exist. He is holding up a sign that says stop listening to this as weather."
      },
      {
       "spk": "nagel",
       "text": "We noticed in nineteen eighty-four. We assumed a fault in the encoder and we filed a report and the report was very long and entirely wrong."
      }
     ]
    }
   ]
  },
  "s21_route": {
   "act": 3,
   "clock": 16,
   "amb": "workstation",
   "title": "Wind backing westerly",
   "grants": [
    "E09"
   ],
   "sets": {
    "decoded_route": true,
    "courier_known": true
   },
   "next": "s19_hub_cipher",
   "id": "s21_route",
   "segments": [
    {
     "asset": "s21_route__00",
     "fx": "workstation",
     "lines": [
      {
       "spk": "iris",
       "text": "Take every wind bearing in sequence and walk them. Not as weather. As instructions."
      },
      {
       "spk": "iris",
       "text": "South south west four. North north east two. It is a route. It starts at the Adlershof transmitter and ends at a border crossing on Friedrichstrasse."
      },
      {
       "spk": "vogt",
       "text": "That is the nineteen eighty-three extraction route."
      },
      {
       "spk": "iris",
       "text": "Yes. And it is also tonight's, because the bearings in tonight's transmission are not the same as eighty-three. Four of them have changed. Whoever is transmitting now has updated the walk for a city that has a different railway."
      },
      {
       "spk": "vogt",
       "text": "Then someone is walking it at this moment. I will call the Bundespolizei-"
      },
      {
       "spk": "dorsey",
       "text": "And say what, Anneke? That a weather report told you a man is going to a train station? You will be a very entertaining recording at somebody's hearing."
      }
     ]
    }
   ]
  },
  "s22_index": {
   "act": 3,
   "clock": 15,
   "amb": "workstation",
   "title": "One one four nine",
   "grants": [
    "E10"
   ],
   "sets": {
    "decoded_index": true
   },
   "next": "s19_hub_cipher",
   "id": "s22_index",
   "segments": [
    {
     "asset": "s22_index__00",
     "fx": "workstation",
     "lines": [
      {
       "spk": "iris",
       "text": "If the pressure values are not weather, they are numbers with nowhere to live. So give them somewhere. Frau Vogt, does this archive use four-digit box references?"
      },
      {
       "spk": "vogt",
       "text": "It uses the Ministry's system. Four digits, then a page. One one four nine would be-"
      },
      {
       "spk": "vogt",
       "text": "Box one one four nine is sealed. Zero nine nine one is sealed. Zero four one seven is sealed. Examiner, all three of the pressure values from tonight are sealed boxes in a building that has been locked since ten o'clock."
      },
      {
       "spk": "nagel",
       "text": "He is giving you the shelf number, and he has been giving it to you since nineteen eighty-four, and you were checking the barometer."
      }
     ]
    }
   ]
  },
  "s23_archive": {
   "act": 3,
   "clock": 14,
   "amb": "vault",
   "title": "Box 1149",
   "grants": [
    "E11",
    "E12"
   ],
   "sets": {
    "found_list": true
   },
   "next": "s25_iris_upload",
   "id": "s23_archive",
   "segments": [
    {
     "asset": "s23_archive__00",
     "fx": "vault",
     "lines": [
      {
       "spk": "vogt",
       "text": "Box one one four nine. March, nineteen eighty-three. It is a distribution receipt."
      },
      {
       "spk": "vogt",
       "text": "Nine cryptonyms. GLASSHOUSE handling list, partial. Released for oral briefing on the ninth of March to a liaison officer, countersigned, and the countersignature is a political office. Not an intelligence office. A political office."
      },
      {
       "spk": "frayne",
       "text": "Read the liaison officer's name."
      },
      {
       "spk": "vogt",
       "text": "G. Dorsey."
      },
      {
       "spk": "frayne",
       "text": "Ah."
      },
      {
       "spk": "dorsey",
       "text": "That briefing was authorised. It was authorised at a level none of you have ever been cleared to know about, and it was authorised for reasons that are still classified and still correct."
      },
      {
       "spk": "iris",
       "text": "Four of those nine were dead within eleven weeks."
      },
      {
       "spk": "dorsey",
       "text": "I know how many."
      }
     ]
    }
   ]
  },
  "s24_insert": {
   "act": 3,
   "clock": 15,
   "amb": "workstation",
   "title": "Nine seconds",
   "req": {
    "flag": "knows_rhythm"
   },
   "grants": [
    "E16"
   ],
   "sets": {
    "found_insert": true
   },
   "next": "s19_hub_cipher",
   "id": "s24_insert",
   "segments": [
    {
     "asset": "s24_insert__00",
     "fx": "workstation",
     "lines": [
      {
       "spk": "iris",
       "text": "I have laid tonight's transmission against my father's rhythm. Three, two, five, in the silences. It holds for the whole broadcast."
      },
      {
       "spk": "iris",
       "text": "Except here. Nine seconds, beginning at one minute four. The words are right. The vocabulary is right. And the gaps are one point two zero zero seconds. Every one of them. To the millisecond."
      },
      {
       "spk": "nagel",
       "text": "A man cannot breathe to the millisecond."
      },
      {
       "spk": "iris",
       "text": "No. A man cannot. Somebody has cut nine seconds into my father's broadcast and set the gaps with a mouse."
      },
      {
       "spk": "vogt",
       "text": "Play the nine seconds."
      }
     ]
    },
    {
     "asset": "s24_insert__01",
     "fx": "insert",
     "lines": [
      {
       "spk": "meteo",
       "text": "Courier. East platform. Destroy blue key. Close glasshouse."
      }
     ]
    },
    {
     "asset": "s24_insert__02",
     "fx": "workstation",
     "lines": [
      {
       "spk": "frayne",
       "text": "That is not a message from nineteen eighty-three, Examiner. That is somebody giving an order this evening, in a dead woman's voice, on a channel we were all too sentimental to switch off."
      }
     ]
    }
   ]
  },
  "s25_iris_upload": {
   "act": 3,
   "clock": 13,
   "amb": "workstation",
   "title": "The eleventh of July",
   "grants": [
    "E13"
   ],
   "sets": {
    "iris_confessed": true,
    "trust_iris": 1
   },
   "next": "s26_hub_network",
   "id": "s25_iris_upload",
   "segments": [
    {
     "asset": "s25_iris_upload__00",
     "fx": "workstation",
     "lines": [
      {
       "spk": "iris",
       "text": "Before anyone else finds it and makes it sound worse than it is. It was me. I woke the station."
      },
      {
       "spk": "vogt",
       "text": "Explain that."
      },
      {
       "spk": "iris",
       "text": "On the eleventh of July I scanned the nineteen eighty-six card and uploaded it to an open cryptography forum. I wanted somebody to tell me it was nothing. It had been thirty-nine years and I wanted a stranger to tell me it was a card from a father to a child."
      },
      {
       "spk": "iris",
       "text": "It was a release condition. He built a lock that opens when the last row of the table becomes public, and he gave the last row to a nine-year-old, and he waited."
      },
      {
       "spk": "frayne",
       "text": "He waited for you to be ready, Iris. Not for the row. That is what the mechanism is for. He had no way to measure whether the world was safe, so he measured whether his daughter had gone looking."
      },
      {
       "spk": "iris",
       "text": "Don't."
      },
      {
       "spk": "frayne",
       "text": "No. Quite right. I apologise."
      }
     ]
    }
   ]
  },
  "s26_hub_network": {
   "act": 4,
   "clock": 11,
   "amb": "vault",
   "title": "Eleven minutes",
   "hub": true,
   "id": "s26_hub_network",
   "segments": [
    {
     "asset": "s26_hub_network__00",
     "fx": "vault",
     "lines": [
      {
       "spk": "vogt",
       "text": "Eleven minutes. There is a courier walking a route out of a weather report, and there are nine seconds in tonight's broadcast that somebody made. I would like to know who, and I would like to know before the window."
      }
     ]
    }
   ],
   "choices": [
    {
     "label": "Take the nine seconds to the analysis bench.",
     "goto": "s27_bench",
     "req": {
      "flag": "found_insert"
     },
     "tag": "net",
     "once": true
    },
    {
     "label": "Who could voice her? Find the recording schedule.",
     "goto": "s28_library",
     "tag": "net",
     "once": true
    },
    {
     "label": "Who opened this archive six months ago?",
     "goto": "s29_credentials",
     "tag": "net",
     "once": true
    },
    {
     "label": "Dorsey. The ninth of March.",
     "goto": "s30_dorsey_admit",
     "req": {
      "flag": "found_list"
     },
     "tag": "net",
     "once": true
    },
    {
     "label": "Frau Vogt: why have you been redacting your own archive?",
     "goto": "s31_vogt_mother",
     "req": {
      "flag": "syllable_gap"
     },
     "tag": "net",
     "once": true
    },
    {
     "label": "Open the last layer of the cipher.",
     "goto": "s32_confession",
     "req": {
      "flag": "iris_confessed",
      "tag_count": [
       "net",
       2
      ]
     }
    }
   ]
  },
  "s27_bench": {
   "act": 4,
   "clock": 10,
   "amb": "bench",
   "bench": true,
   "title": "Analysis bench",
   "next": "s26_hub_network",
   "id": "s27_bench",
   "segments": [
    {
     "asset": "s27_bench__00",
     "fx": "bench",
     "lines": [
      {
       "spk": "vogt",
       "text": "Nine seconds, isolated and looped. The bench will do whatever you ask it and nothing you do not. Choose carefully, we are short of minutes."
      }
     ]
    }
   ],
   "bench_options": [
    {
     "id": "slow",
     "label": "Slow to half speed, preserve pitch",
     "correct": false,
     "cost": 1,
     "result": "The words separate. Courier. East platform. Nothing new in them; they were always clear. The evenness gets worse the slower it goes.",
     "asset": "s27_bench__bench_slow",
     "line": {
      "spk": "iris",
      "text": "It is cleaner slowed down, which is itself an answer. Tape is never cleaner slowed down."
     }
    },
    {
     "id": "speech",
     "label": "Isolate the speech band, 300 to 3400 hertz",
     "correct": false,
     "cost": 1,
     "result": "The announcer, alone, with everything else stripped away. Flawless. Too flawless.",
     "asset": "s27_bench__bench_speech",
     "line": {
      "spk": "nagel",
      "text": "You have removed the room. In my day we would have called that destroying the evidence, but very politely."
     }
    },
    {
     "id": "floor",
     "label": "Gate the speech. Lift the noise floor between phrases.",
     "correct": true,
     "cost": 1,
     "result": "Under the announcer there is a room. A metallic tick, regular, every 2.1 seconds. Beneath it, once, a long low rumble that rises and falls away.",
     "asset": "s27_bench__bench_floor",
     "line": {
      "spk": "iris",
      "text": "There is a room under her. A tick, every two seconds or so, absolutely regular. And once, something heavy going past outside."
     }
    },
    {
     "id": "compare",
     "label": "Compare that room against the 1983 archive.",
     "correct": true,
     "cost": 1,
     "req": "bench_floor",
     "result": "The 1983 station recordings have a room too: a large, dead, curtained studio. This is a small room with a radiator and a tram line.",
     "asset": "s27_bench__bench_compare",
     "line": {
      "spk": "vogt",
      "text": "The eighty-three recordings were made in a treated studio. There is no radiator in Adlershof and there is no tram. Examiner, this room is not in nineteen eighty-three. This room is somewhere tonight."
     }
    }
   ],
   "on_correct": {
    "grants": [
     "E17"
    ],
    "sets": {
     "room_tone": true
    }
   }
  },
  "s28_library": {
   "act": 4,
   "clock": 10,
   "amb": "vault",
   "title": "The word list",
   "grants": [
    "E18"
   ],
   "sets": {
    "syllable_gap": true
   },
   "next": "s26_hub_network",
   "id": "s28_library",
   "segments": [
    {
     "asset": "s28_library__00",
     "fx": "vault",
     "lines": [
      {
       "spk": "vogt",
       "text": "Box zero four one seven. The station's own file. Recording schedules, nineteen seventy-nine to nineteen eighty-six."
      },
      {
       "spk": "vogt",
       "text": "The announcer attended eleven sessions. She read a fixed vocabulary. Numbers zero to nine. Cardinal points. Cloud states. Twelve nouns. That is the entire language of Station four one seven. Nine hundred and forty words."
      },
      {
       "spk": "iris",
       "text": "Platform is not a cloud state."
      },
      {
       "spk": "vogt",
       "text": "No. Platform is not on the list. Courier is not on the list. Neither word exists in any session she ever recorded, and neither can be assembled from the syllables of the ones that do. I have had the system check."
      },
      {
       "spk": "iris",
       "text": "Then tonight, somebody made her say two words she never said. Not cut. Made."
      },
      {
       "spk": "nagel",
       "text": "That would require her voice. All of it. Not the tapes the archive holds. The session masters."
      },
      {
       "spk": "vogt",
       "text": "Which were destroyed in nineteen ninety."
      },
      {
       "spk": "nagel",
       "text": "Which were signed for as destroyed in nineteen ninety. It was a busy spring. A great many things were signed for."
      }
     ]
    }
   ]
  },
  "s29_credentials": {
   "act": 4,
   "clock": 9,
   "amb": "vault",
   "title": "An officer who died in 2007",
   "grants": [
    "E14"
   ],
   "sets": {
    "knows_credentials": true
   },
   "next": "s26_hub_network",
   "id": "s29_credentials",
   "segments": [
    {
     "asset": "s29_credentials__00",
     "fx": "vault",
     "lines": [
      {
       "spk": "vogt",
       "text": "I have been sitting on this for four hours and I am going to say it badly. On the sixth of February somebody opened this archive's audio holdings using a valid credential."
      },
      {
       "spk": "vogt",
       "text": "The credential belongs to Oberst Manfred Reuss, who was cleared for this material in nineteen ninety-four, and who died in Rostock in two thousand and seven."
      },
      {
       "spk": "frayne",
       "text": "What did the dead man look at?"
      },
      {
       "spk": "vogt",
       "text": "Four hours of Station four one seven session material. He did not copy the transcripts. He copied only the audio, and only the sessions where she is alone in the room."
      },
      {
       "spk": "iris",
       "text": "That's not an intelligence officer stealing a secret. That's somebody collecting clean voice samples."
      },
      {
       "spk": "dorsey",
       "text": "Or it's a researcher with a dead man's password, and we are constructing a monster out of a filing error while an actual courier walks to an actual station."
      }
     ]
    }
   ]
  },
  "s30_dorsey_admit": {
   "act": 4,
   "clock": 8,
   "amb": "line",
   "title": "The ninth of March",
   "grants": [],
   "sets": {
    "dorsey_admitted": true
   },
   "next": "s26_hub_network",
   "id": "s30_dorsey_admit",
   "segments": [
    {
     "asset": "s30_dorsey_admit__00",
     "fx": "line",
     "lines": [
      {
       "spk": "dorsey",
       "text": "You want the ninth of March. All right. I'll give you the ninth of March, and then I'd like somebody to notice what it isn't."
      },
      {
       "spk": "dorsey",
       "text": "In March of eighty-three there was a vote coming that would have put our people out of three cities. I needed a man in a political office to believe that the network was worth the trouble. So I read him nine cryptonyms. Not names. Cryptonyms."
      },
      {
       "spk": "frayne",
       "text": "You read nine cryptonyms to a politician."
      },
      {
       "spk": "dorsey",
       "text": "I read nine cryptonyms to a man with a safe and a clearance, and he repeated four of them to an aide who did not have either, and that aide talked at a dinner in Bonn, and eleven weeks later four people were dead."
      },
      {
       "spk": "dorsey",
       "text": "I have known that since November of eighty-three. I did not sell anybody. I was careless in a building where careless is the same as murder, and I have spent forty-three years being extremely useful to make up for it."
      },
      {
       "spk": "iris",
       "text": "And Willi Kroll?"
      },
      {
       "spk": "dorsey",
       "text": "Kroll was the shape the investigation was already making. I did not put him there."
      },
      {
       "spk": "iris",
       "text": "Did you take him out of it?"
      },
      {
       "spk": "dorsey",
       "text": "No."
      }
     ]
    }
   ]
  },
  "s32_confession": {
   "act": 4,
   "clock": 7,
   "amb": "workstation",
   "title": "The last layer",
   "grants": [
    "E19"
   ],
   "sets": {
    "has_confession": true
   },
   "next": "s33_courier",
   "id": "s32_confession",
   "segments": [
    {
     "asset": "s32_confession__00",
     "fx": "workstation",
     "lines": [
      {
       "spk": "iris",
       "text": "The eighth row of the table is the last substitution. I have never run it because I have never had all eight rows in the same room as the broadcast. It is running now."
      },
      {
       "spk": "vogt",
       "text": "How long?"
      },
      {
       "spk": "iris",
       "text": "It's done. It's a voice file. He left a voice file."
      }
     ]
    },
    {
     "asset": "s32_confession__01",
     "fx": "tape91",
     "lines": [
      {
       "spk": "halloway",
       "text": "This will be very late reaching you and I am sorry for that. If you are hearing it, then the last card is public, which means Iris went looking, which means she is well, which is the only part of this I have ever actually wanted to know."
      },
      {
       "spk": "halloway",
       "text": "The compromise was not a traitor. It was a briefing. Gene Dorsey read nine cryptonyms to a political office in March of eighty-three and the room leaked, as rooms do. The archive reference is one one four nine."
      },
      {
       "spk": "halloway",
       "text": "Willi Kroll did not betray anybody. I believed he had. I was wrong in the way that only a careful man can be wrong, which is slowly and with a great deal of arithmetic."
      },
      {
       "spk": "halloway",
       "text": "On the fifteenth of October, at a crossing on Friedrichstrasse, Willi Kroll had an envelope containing six names and he was going to hand it across to buy himself a night's sleep. He was not a wicked man. He was a frightened one, and I have been both."
      },
      {
       "spk": "halloway",
       "text": "I killed him. I want that in the plainest available English. Not a struggle. Not an accident. I stood in front of a man I had wronged and I made a decision and then I carried it out, and six people I have never met are grandmothers."
      },
      {
       "spk": "halloway",
       "text": "So I have chained the two together. You cannot have Dorsey without having me. If that seems unfair to you, consider that it is the only fair thing in the entire affair. A man who has done what I have done does not get to be the one who accuses."
      },
      {
       "spk": "halloway",
       "text": "Iris. The forecast is memory. It means the weather has already happened. It means you cannot be warned, only told. I have told you. I am sorry it is this."
      },
      {
       "spk": "halloway",
       "text": "Weathervane out."
      }
     ]
    }
   ]
  },
  "s33_courier": {
   "act": 4,
   "clock": 5,
   "amb": "vault",
   "title": "East platform",
   "next": "s34_confront",
   "id": "s33_courier",
   "segments": [
    {
     "asset": "s33_courier__00",
     "fx": "vault",
     "lines": [
      {
       "spk": "vogt",
       "text": "Bundespolizei have a man on the east platform at Ostbahnhof matching a route that does not officially exist. He is carrying a case. They will not move without an authority and I do not have one."
      },
      {
       "spk": "vogt",
       "text": "Five minutes to the window. Examiner, this is the part where you stop listening and start being responsible for something."
      }
     ]
    }
   ]
  },
  "s34_confront": {
   "act": 4,
   "clock": 4,
   "amb": "apartment",
   "confront": true,
   "title": "Nagel",
   "accuse_prompt": "Put it to him. Choose what you put.",
   "next": "s35_theory",
   "id": "s34_confront",
   "segments": [
    {
     "asset": "s34_confront__00",
     "fx": "apartment",
     "lines": [
      {
       "spk": "nagel",
       "text": "You have gone quiet, Examiner. In my experience that means either you have understood something, or you are about to embarrass yourself. Both are entertaining."
      }
     ]
    }
   ],
   "challenges": [
    {
     "id": "seam",
     "label": "\"You spoke the seam a half-second before the tape played it.\"",
     "correct": true,
     "req": "nagel_slip",
     "cost": 0,
     "segments": [
      {
       "asset": "s34_confront__ch_seam_00",
       "fx": "apartment",
       "lines": [
        {
         "spk": "nagel",
         "text": "I have heard that recording many times."
        },
        {
         "spk": "iris",
         "text": "You told us you never filed it. You told us it was not in anyone's archive. There is no copy of that tape for you to have heard many times. There is only the one you kept."
        },
        {
         "spk": "nagel",
         "text": "[a long breath] That is a good point. That is a very good point."
        }
       ]
      }
     ]
    },
    {
     "id": "room",
     "label": "\"The insert is breathing in your flat. Radiator. Tram.\"",
     "correct": true,
     "req": "room_tone",
     "cost": 0,
     "segments": [
      {
       "asset": "s34_confront__ch_room_00",
       "fx": "apartment",
       "lines": [
        {
         "spk": "vogt",
         "text": "Herr Nagel, there is a radiator behind you. It ticks every two point one seconds. It has ticked three times since you began speaking and I have counted every one of them."
        },
        {
         "spk": "nagel",
         "text": "You are aware how many flats in this city have a radiator."
        },
        {
         "spk": "vogt",
         "text": "Under the nine seconds there is a tick every two point one seconds. Same period. Same decay. And a tram passes at the same offset from it as the one that passed your window while you were denying this."
        },
        {
         "spk": "vogt",
         "text": "It is not a flat with a radiator, Herr Nagel. It is your radiator, and it is in tonight's broadcast."
        }
       ]
      }
     ]
    },
    {
     "id": "word",
     "label": "\"'Platform' isn't in her word list. Somebody built it.\"",
     "correct": true,
     "req": "syllable_gap",
     "cost": 0,
     "segments": [
      {
       "asset": "s34_confront__ch_word_00",
       "fx": "apartment",
       "lines": [
        {
         "spk": "nagel",
         "text": "Then somebody had the session masters."
        },
        {
         "spk": "iris",
         "text": "Somebody who knew there were session masters. Everyone else in this call believed they were destroyed in ninety. You corrected us. Nobody asked you to."
        },
        {
         "spk": "nagel",
         "text": "Ah."
        }
       ]
      }
     ]
    },
    {
     "id": "stasi",
     "label": "\"You were Stasi. You have always been the obvious answer.\"",
     "correct": false,
     "req": null,
     "cost": 1,
     "segments": [
      {
       "asset": "s34_confront__ch_stasi_00",
       "fx": "apartment",
       "lines": [
        {
         "spk": "nagel",
         "text": "Yes. I was. And for forty years that sentence has been the cheapest one available in this country, and every time somebody reaches for it they stop thinking about ninety seconds too early."
        },
        {
         "spk": "dorsey",
         "text": "He's right, Examiner. And you just spent a minute you didn't have."
        }
       ]
      }
     ]
    },
    {
     "id": "rhythm",
     "label": "\"You knew the three-two-five rhythm. Only the forger would.\"",
     "correct": false,
     "req": null,
     "cost": 1,
     "segments": [
      {
       "asset": "s34_confront__ch_rhythm_00",
       "fx": "apartment",
       "lines": [
        {
         "spk": "nagel",
         "text": "I knew it because I spent eleven years failing to break it. It is in my service file. It is in the file you are sitting on top of, Frau Vogt, box zero four one seven, page ninety."
        },
        {
         "spk": "vogt",
         "text": "...It is. It is on page ninety."
        }
       ]
      }
     ]
    }
   ],
   "break_lines": [
    {
     "asset": "s34_confront__break_00",
     "fx": "apartment",
     "lines": [
      {
       "spk": "nagel",
       "text": "Forty-one years ago they gave me a woman's voice in a box and told me to make her say whatever the service required. I was twenty-two. I was very good at it."
      },
      {
       "spk": "nagel",
       "text": "In ninety I was told to destroy her and I signed the paper and I did not do it. Everyone was destroying things that spring. I saved the only thing I had ever made properly."
      },
      {
       "spk": "nagel",
       "text": "And then, Examiner, nothing happened for a very long time. And then people began to want voices again. Different people. Better paid."
      },
      {
       "spk": "nagel",
       "text": "I did not know whose order I was carrying tonight. I have never known. That is the service they are buying. I was given nine seconds of text and a window, and I put her on the air one last time."
      },
      {
       "spk": "nagel",
       "text": "I did help your father, Doctor Halloway. That was also true. A man can do one decent thing in nineteen eighty-three and be a supplier in twenty twenty-six. Nobody is a single sentence."
      }
     ]
    }
   ],
   "fail_lines": [
    {
     "asset": "s34_confront__fail__00",
     "fx": "apartment",
     "lines": [
      {
       "spk": "nagel",
       "text": "You have four minutes and you have spent them on me. I am flattered, and you are finished."
      }
     ]
    }
   ]
  },
  "s35_theory": {
   "act": 5,
   "clock": 3,
   "amb": "vault",
   "theory": true,
   "title": "Submit your finding",
   "questions": [
    {
     "id": "insert",
     "prompt": "Who put nine seconds into tonight's broadcast?",
     "options": [
      [
       "nagel",
       "Ulrich Nagel",
       true
      ],
      [
       "dorsey",
       "Gene Dorsey",
       false
      ],
      [
       "frayne",
       "Dame Rosalind Frayne",
       false
      ],
      [
       "iris",
       "Iris Halloway",
       false
      ],
      [
       "vogt",
       "Anneke Vogt",
       false
      ],
      [
       "unknown",
       "A client whose name nobody here knows",
       false
      ]
     ]
    },
    {
     "id": "compromise",
     "prompt": "Who compromised GLASSHOUSE in 1983?",
     "options": [
      [
       "dorsey",
       "Gene Dorsey, by briefing a political office",
       true
      ],
      [
       "kroll",
       "Willi Kroll, the courier",
       false
      ],
      [
       "halloway",
       "Peter Halloway, who defected",
       false
      ],
      [
       "frayne",
       "Dame Rosalind Frayne, who falsified the log",
       false
      ],
      [
       "nagel",
       "Ulrich Nagel, listening from the East",
       false
      ]
     ]
    },
    {
     "id": "kroll",
     "prompt": "What happened to Willi Kroll?",
     "options": [
      [
       "halloway",
       "Halloway killed him at the crossing",
       true
      ],
      [
       "stasi",
       "The Stasi took him",
       false
      ],
      [
       "framed",
       "He was framed and disappeared",
       false
      ],
      [
       "unknown",
       "The record does not say",
       false
      ]
     ]
    }
   ],
   "next": "s36_disclosure",
   "id": "s35_theory",
   "segments": [
    {
     "asset": "s35_theory__00",
     "fx": "vault",
     "lines": [
      {
       "spk": "vogt",
       "text": "Three minutes. The finding goes on the record in three parts and it goes on my authority, which means if you are wrong I lose this building and you lose rather more. Speak."
      }
     ]
    }
   ]
  },
  "s36_disclosure": {
   "act": 5,
   "clock": 2,
   "amb": "vault",
   "disclosure": true,
   "title": "The window",
   "options": [
    {
     "id": "redacted",
     "label": "Release the accusation and the confession. Redact the names.",
     "desc": "Dorsey's briefing and Halloway's killing, both. The protected persons schedule stays sealed."
    },
    {
     "id": "suppress",
     "label": "Release nothing. Seal it and let the window close.",
     "desc": "Four families stay invisible. So does everything else."
    },
    {
     "id": "total",
     "label": "Release everything, unredacted.",
     "desc": "The file as it is, names included. Let it be judged whole."
    }
   ],
   "id": "s36_disclosure",
   "segments": [
    {
     "asset": "s36_disclosure__00",
     "fx": "vault",
     "lines": [
      {
       "spk": "vogt",
       "text": "Ninety seconds. The transmitter will carry whatever we give it. Everything in the file, nothing in the file, or the part that can be said without a name in it. Choose, Examiner."
      },
      {
       "spk": "iris",
       "text": "Whatever you send, send all of him. Not the useful half. He chained them together so that nobody could do to him what he did to Willi Kroll. If you unchain them to make him a martyr, you have learned nothing tonight."
      }
     ]
    }
   ]
  },
  "s31_vogt_mother": {
   "act": 4,
   "clock": 8,
   "amb": "vault",
   "title": "Why she took the posting",
   "sets": {
    "vogt_mother": true,
    "trust_vogt": 1
   },
   "next": "s26_hub_network",
   "id": "s31_vogt_mother",
   "segments": [
    {
     "asset": "s31_vogt_mother__00",
     "fx": "vault",
     "lines": [
      {
       "spk": "iris",
       "text": "Frau Vogt. You have been redacting this collection for four years. I have seen the version history. Nine hundred entries, all of them family names, all of them yours to approve."
      },
      {
       "spk": "vogt",
       "text": "Yes."
      },
      {
       "spk": "iris",
       "text": "Why?"
      },
      {
       "spk": "vogt",
       "text": "Because in nineteen eighty-three a woman in Adlershof read a list into a microphone eleven times, and she was not paid, and she was not asked, and she was told what would happen to her daughter if she declined."
      },
      {
       "spk": "iris",
       "text": "...Ilse Vogt."
      },
      {
       "spk": "vogt",
       "text": "Ilse Vogt. She died in two thousand and four, in Pankow, having never once told me what she did. I found out from a card index. I took this posting fourteen months later."
      },
      {
       "spk": "vogt",
       "text": "So yes. I have been removing names. I have not removed one fact, one date, or one crime. I have removed the addresses of frightened people. If that ends my career, then a great many people in this story have paid more for less."
      },
      {
       "spk": "nagel",
       "text": "[very quietly] I did not know she had a daughter."
      },
      {
       "spk": "vogt",
       "text": "You had her voice for forty years, Herr Nagel. You never once wondered whose it was."
      }
     ]
    }
   ]
  },
  "end_forecast": {
   "act": 6,
   "clock": 0,
   "amb": "vault",
   "ending": true,
   "title": "Ending: The Forecast Is Memory",
   "ending_id": "forecast",
   "id": "end_forecast",
   "segments": [
    {
     "asset": "end_forecast__00",
     "fx": "vault",
     "lines": [
      {
       "spk": "vogt",
       "text": "Finding entered. Ulrich Nagel, insertion of a covert instruction into a civil broadcast. Gene Dorsey, unauthorised disclosure, March nineteen eighty-three. Willi Kroll, exonerated of espionage, unlawfully killed. Transmitting the redacted file."
      },
      {
       "spk": "vogt",
       "text": "Bundespolizei took the courier on the east platform at four minutes past. The case held a one-time pad and a phone with one number in it. The number is disconnected. It has been disconnected since before the arrest."
      },
      {
       "spk": "frayne",
       "text": "Of course it is. You have cut one wire out of a switchboard, Examiner. Do not mistake that for the end of the exchange. But it was the correct wire, and it has been forty-three years, and I find I am not sorry."
      },
      {
       "spk": "iris",
       "text": "They will make him a villain by Thursday. Both of them. My father killed a frightened man at a border and then spent eight years posting the proof to a child, and there is no headline that holds both halves of that."
      },
      {
       "spk": "iris",
       "text": "But it is out, and it is whole, and Willi Kroll's sister is eighty-one and can read it tomorrow. That will do. That will have to do."
      },
      {
       "spk": "vogt",
       "text": "Examiner. Herr Nagel has sent one further file from custody. It is not evidence. He has marked it, in English, personal."
      },
      {
       "spk": "nagel",
       "text": "Session four, nineteen eighty-one. Between takes. I never cut this one because there was nothing in it I could use. Frau Vogt, I am too old to apologise usefully. Take it anyway."
      }
     ]
    },
    {
     "asset": "end_forecast__01",
     "fx": "reel81",
     "lines": [
      {
       "spk": "meteo",
       "text": "Is it still running? It is still running. Oh - one moment - my daughter has a concert this evening and I have promised, so if we could possibly-"
      },
      {
       "spk": "meteo",
       "text": "Yes. Sorry. Ready."
      },
      {
       "spk": "meteo",
       "text": "Wind, south south west, four. Cloud, broken. Visibility, three."
      }
     ]
    }
   ],
   "coda_total": [
    {
     "asset": "end_forecast__coda__00",
     "fx": "vault",
     "lines": [
      {
       "spk": "vogt",
       "text": "One correction to the record. You released the file entire. At eleven minutes past, a woman in Schwerin rang this facility to ask why her mother's name is on the internet. I did not have an answer for her. I do not have one now."
      }
     ]
    }
   ]
  },
  "end_necessary_lie": {
   "act": 6,
   "clock": 0,
   "amb": "vault",
   "ending": true,
   "title": "Ending: The Necessary Lie",
   "ending_id": "necessary_lie",
   "id": "end_necessary_lie",
   "segments": [
    {
     "asset": "end_necessary_lie__00",
     "fx": "vault",
     "lines": [
      {
       "spk": "vogt",
       "text": "The window has closed. Nothing was transmitted. The finding is sealed under the continuity provision for ninety-nine years, which means all of us will be dead and so will anyone who cared."
      },
      {
       "spk": "vogt",
       "text": "Herr Nagel was collected at his flat at twenty past. There will be no charge. There will be an arrangement. The courier was allowed to board."
      },
      {
       "spk": "dorsey",
       "text": "You did the adult thing, Examiner, and nobody is ever going to tell you so. Four families went to bed tonight not knowing there was a decision about them. That's the whole job. That was always the whole job."
      },
      {
       "spk": "frayne",
       "text": "Gene, if you thank the examiner one more time I shall come to Virginia."
      },
      {
       "spk": "iris",
       "text": "I have been given a copy. Personal use. Not to be reproduced. Forty years, and my inheritance is a file I am not allowed to show anyone."
      },
      {
       "spk": "iris",
       "text": "He killed a man to keep six names quiet and you have kept his name quiet to protect four more, and I cannot tell any longer whether that is the moral of the story or just the story repeating."
      },
      {
       "spk": "vogt",
       "text": "Examiner. The carrier is still up. There is no modulation on it. There has been no modulation for six minutes."
      },
      {
       "spk": "vogt",
       "text": "It is simply open. As though something is waiting to see whether we will say anything at all."
      }
     ]
    }
   ]
  },
  "end_repeated": {
   "act": 6,
   "clock": 0,
   "amb": "shortwave",
   "ending": true,
   "title": "Ending: You Have Repeated 1983",
   "ending_id": "repeated",
   "id": "end_repeated",
   "segments": [
    {
     "asset": "end_repeated__00",
     "fx": "shortwave",
     "lines": [
      {
       "spk": "vogt",
       "text": "The window is open. The transmission is going out and I cannot stop it from this room."
      },
      {
       "spk": "meteo",
       "text": "Achtung. Station four one seven. Wind, west, two. Cloud, overcast. Visibility, one. Pressure, one one four nine."
      }
     ]
    },
    {
     "asset": "end_repeated__01",
     "fx": "insert",
     "lines": [
      {
       "spk": "meteo",
       "text": "Courier confirmed. Blue key destroyed. Glasshouse closed."
      }
     ]
    },
    {
     "asset": "end_repeated__02",
     "fx": "shortwave",
     "lines": [
      {
       "spk": "vogt",
       "text": "The courier boarded at four minutes past. The case was opened at Erkner and the pad had already been burned. The archive was seized at half past under the continuity provision. I am told my access ends at midnight."
      },
      {
       "spk": "iris",
       "text": "You named a person. You had four minutes and a room full of recordings, and you named a person, because that is what everybody does. That is what my father did to Willi Kroll."
      },
      {
       "spk": "frayne",
       "text": "It is nineteen eighty-three again, and this time I watched it happen in real time, on a conference line, with the countdown showing. Good night, Examiner."
      },
      {
       "spk": "vogt",
       "text": "Examiner - the station has not closed down. It is still transmitting. This is not in tonight's schedule. This is new material."
      },
      {
       "spk": "meteo",
       "text": "Message follows. Review terminal, seven, four, one, nine. Examiner present. Examiner listening. Examiner logged."
      },
      {
       "spk": "meteo",
       "text": "The forecast is memory. Ends."
      }
     ]
    }
   ]
  },
  "s23b_rhythm_alt": {
   "act": 3,
   "clock": 15,
   "amb": "workstation",
   "title": "The silences",
   "grants": [
    "E15"
   ],
   "sets": {
    "knows_rhythm": true
   },
   "next": "s19_hub_cipher",
   "id": "s23b_rhythm_alt",
   "segments": [
    {
     "asset": "s23b_rhythm_alt__00",
     "fx": "workstation",
     "lines": [
      {
       "spk": "iris",
       "text": "I have been looking at the wrong part of the signal all evening. I have been looking at the sound."
      },
      {
       "spk": "iris",
       "text": "My father's entire discipline was that sound can be forged and structure cannot. So measure the gaps. Eighty-one, eighty-three, tonight."
      },
      {
       "spk": "iris",
       "text": "Three beats. Two beats. Five beats. In every authentic transmission, in the silence between the phrases, for forty-five years."
      },
      {
       "spk": "vogt",
       "text": "Does three, two, five mean anything?"
      },
      {
       "spk": "iris",
       "text": "The third of the second, nineteen seventy-five. It's my birthday, Frau Vogt. He signed forty-five years of transmissions with my birthday and no one on either side ever thought to check the parts where nobody was talking."
      }
     ]
    }
   ]
  }
 },
 "evidence": {
  "E01": {
   "name": "Tonight's broadcast",
   "surface": "Station 417, live at T-28.",
   "truth": "Carries two messages laid over each other."
  },
  "E02": {
   "name": "Halloway's last transmission",
   "surface": "Recorded 14 October 1983.",
   "truth": "Contains the authentication rhythm in its gaps."
  },
  "E03": {
   "name": "Birthday card, 1986",
   "surface": "A child's card with a weather phrase.",
   "truth": "Teaches the final substitution rule."
  },
  "E04": {
   "name": "Frayne's operational log",
   "surface": "Halloway assessed unstable, 12 Oct.",
   "truth": "The entry was written after he vanished, not before."
  },
  "E05": {
   "name": "Checkpoint recording",
   "surface": "A confused crossing, 14 October.",
   "truth": "There is a third man on the tape, and he is not shouting."
  },
  "E06": {
   "name": "Kroll's unsent letter",
   "surface": "A field officer's last statement.",
   "truth": "He knew he was being prepared as the culprit."
  },
  "E07": {
   "name": "Nagel's private tape",
   "surface": "Stasi monitoring, unlogged.",
   "truth": "Genuine - and he knows its seams too well."
  },
  "E08": {
   "name": "Meteorological report",
   "surface": "The readings, checked.",
   "truth": "No such weather has ever occurred anywhere."
  },
  "E09": {
   "name": "Wind route",
   "surface": "Bearings plotted as a path.",
   "truth": "The 1983 extraction route. Tonight's courier is walking it."
  },
  "E10": {
   "name": "Pressure indices",
   "surface": "1149, 0991, 0417.",
   "truth": "Archive box numbers, not barometry."
  },
  "E11": {
   "name": "GLASSHOUSE list fragment",
   "surface": "Nine names, partially redacted.",
   "truth": "Left Dorsey's desk through an unapproved channel in March 1983."
  },
  "E12": {
   "name": "Protected persons schedule",
   "surface": "Survivors and their families.",
   "truth": "Why Halloway built a lock instead of a broadcast."
  },
  "E13": {
   "name": "Upload record",
   "surface": "A scanned card, a public archive, 11 July.",
   "truth": "The release condition Halloway set, tripped by accident."
  },
  "E14": {
   "name": "Expired credentials",
   "surface": "Archive access, six months ago.",
   "truth": "Belonged to an officer who died in 2007."
  },
  "E15": {
   "name": "Authentication rhythm",
   "surface": "Three, two, five - in the silences.",
   "truth": "Halloway's signature. It cannot be typed, only breathed."
  },
  "E16": {
   "name": "Timing mismatch",
   "surface": "Nine seconds of tonight's broadcast.",
   "truth": "Correct words. Even gaps. Placed by a machine."
  },
  "E17": {
   "name": "Room tone",
   "surface": "Beneath the insert: a tick, and a tram.",
   "truth": "The same radiator you can hear on Nagel's line."
  },
  "E18": {
   "name": "The word list",
   "surface": "Ilse Vogt's recording schedule, 1983.",
   "truth": "Every syllable the station could ever say. 'Platform' is not on it."
  },
  "E19": {
   "name": "The last layer",
   "surface": "Halloway's own voice, decoded.",
   "truth": "A confession he chained to his accusation on purpose."
  }
 },
 "speakers": {
  "vogt": {
   "name": "Anneke Vogt",
   "f0": 188.2
  },
  "frayne": {
   "name": "Dame Rosalind Frayne",
   "f0": 158.4
  },
  "nagel": {
   "name": "Ulrich Nagel",
   "f0": 115.1
  },
  "iris": {
   "name": "Iris Halloway",
   "f0": 177.8
  },
  "dorsey": {
   "name": "Gene Dorsey",
   "f0": 132.2
  },
  "halloway": {
   "name": "Dr. Peter Halloway",
   "f0": 137.9
  },
  "kroll": {
   "name": "Willi Kroll",
   "f0": 95.8
  },
  "meteo": {
   "name": "The Meteorologist",
   "f0": 214.8
  }
 },
 "start": "s01_broadcast"
};
