import { describe, expect, it } from 'vitest';
import { compile } from '../src/dbml';
import { toSQL } from '../src/sql/export';
import { fromSQL } from '../src/sql/import';

const SHOP = `
  Enum order_status {
    pending
    shipped
  }

  Table users {
    id int [pk, increment]
    email varchar(255) [not null, unique, note: 'login']
    created_at timestamp [default: \`now()\`]
    Note: 'people who buy things'
  }

  Table orders {
    id int [pk, increment]
    user_id int [not null]
    status order_status
    total decimal(10,2) [default: 0]
    indexes {
      (user_id, status) [name: 'idx_user_status']
    }
  }

  Ref: orders.user_id > users.id [delete: cascade]
`;

describe('SQL export', () => {
  it('emits PostgreSQL DDL', () => {
    const { schema } = compile(SHOP);
    const sql = toSQL(schema, { dialect: 'postgres' });

    expect(sql).toContain(`CREATE TYPE "order_status" AS ENUM ('pending', 'shipped');`);
    expect(sql).toContain(`CREATE TABLE "users" (`);
    expect(sql).toContain(`"id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`);
    expect(sql).toContain(`"email" varchar(255) NOT NULL UNIQUE`);
    expect(sql).toContain(`"created_at" timestamp DEFAULT (now())`);
    expect(sql).toContain(`"status" "order_status"`);
    expect(sql).toContain(`CREATE INDEX "idx_user_status" ON "orders" ("user_id", "status");`);
    expect(sql).toContain(
      `ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;`,
    );
    expect(sql).toContain(`COMMENT ON TABLE "users" IS 'people who buy things';`);
  });

  it('emits MySQL DDL', () => {
    const { schema } = compile(SHOP);
    const sql = toSQL(schema, { dialect: 'mysql' });

    expect(sql).toContain('CREATE TABLE `users` (');
    expect(sql).toContain('`id` int AUTO_INCREMENT PRIMARY KEY');
    expect(sql).toContain("`email` varchar(255) NOT NULL UNIQUE COMMENT 'login'");
    expect(sql).toContain("`status` ENUM('pending', 'shipped')");
    expect(sql).toContain("COMMENT = 'people who buy things'");
    // Enums are inline in MySQL, so no CREATE TYPE.
    expect(sql).not.toContain('CREATE TYPE');
  });

  it('writes composite primary keys as a table constraint', () => {
    const { schema } = compile(`
      Table memberships {
        user_id int [pk]
        team_id int [pk]
      }
    `);
    const sql = toSQL(schema, { dialect: 'postgres' });
    expect(sql).toContain('PRIMARY KEY ("user_id", "team_id")');
  });

  it('qualifies non-default schemas', () => {
    const { schema } = compile(`Table shop.items { id int [pk] }`);
    const sql = toSQL(schema, { dialect: 'postgres' });
    expect(sql).toContain('CREATE SCHEMA IF NOT EXISTS "shop";');
    expect(sql).toContain('CREATE TABLE "shop"."items"');
  });

  it('skips many-to-many refs, which need a join table', () => {
    const { schema } = compile(`
      Table a { id int [pk] }
      Table b { id int [pk] }
      Ref: a.id <> b.id
    `);
    expect(toSQL(schema, { dialect: 'postgres' })).not.toContain('FOREIGN KEY');
  });
});

describe('SQL import', () => {
  it('imports tables, keys, defaults and comments', () => {
    const { dbml } = fromSQL(`
      CREATE TABLE users (
        id SERIAL PRIMARY KEY,
        email VARCHAR(255) NOT NULL UNIQUE,
        role VARCHAR(20) DEFAULT 'member',
        created_at TIMESTAMP DEFAULT now()
      );
      COMMENT ON TABLE users IS 'people';
    `);

    expect(dbml).toContain('Table users {');
    expect(dbml).toContain('id int [pk, increment]');
    expect(dbml).toContain('email VARCHAR(255) [unique, not null]');
    expect(dbml).toContain("role VARCHAR(20) [default: 'member']");
    expect(dbml).toContain('created_at TIMESTAMP [default: `now()`]');
    expect(dbml).toContain("Note: 'people'");
  });

  it('imports foreign keys from inline and ALTER forms', () => {
    const { dbml } = fromSQL(`
      CREATE TABLE users (id INT PRIMARY KEY);
      CREATE TABLE posts (
        id INT PRIMARY KEY,
        user_id INT REFERENCES users (id) ON DELETE CASCADE
      );
      CREATE TABLE tags (id INT PRIMARY KEY, post_id INT);
      ALTER TABLE tags ADD CONSTRAINT fk_post FOREIGN KEY (post_id) REFERENCES posts (id);
    `);
    expect(dbml).toContain('Ref: posts.user_id > users.id [delete: cascade]');
    expect(dbml).toContain('Ref: tags.post_id > posts.id');
  });

  it('imports composite keys, indexes and enums', () => {
    const { dbml } = fromSQL(`
      CREATE TYPE order_status AS ENUM ('pending', 'shipped');
      CREATE TABLE memberships (
        user_id INT NOT NULL,
        team_id INT NOT NULL,
        status order_status,
        PRIMARY KEY (user_id, team_id)
      );
      CREATE UNIQUE INDEX idx_team ON memberships USING btree (team_id, user_id);
    `);
    expect(dbml).toContain('Enum order_status {');
    expect(dbml).toContain('(user_id, team_id) [pk]');
    expect(dbml).toContain("(team_id, user_id) [name: 'idx_team', unique, type: btree]");
  });

  it('handles MySQL backticks and AUTO_INCREMENT', () => {
    const { dbml } = fromSQL(`
      CREATE TABLE \`order items\` (
        \`id\` INT NOT NULL AUTO_INCREMENT,
        \`qty\` INT DEFAULT 1 COMMENT 'how many',
        PRIMARY KEY (\`id\`)
      );
    `);
    expect(dbml).toContain('Table "order items" {');
    expect(dbml).toContain('id INT [pk, increment]');
    expect(dbml).toContain("qty INT [default: 1, note: 'how many']");
  });

  it('reports statements it could not use', () => {
    const { skipped } = fromSQL(`CREATE TABLE a (id INT); GRANT SELECT ON a TO bob;`);
    expect(skipped).toEqual(['GRANT SELECT ON a TO bob']);
  });

  it('round-trips through the compiler without errors', () => {
    const { dbml } = fromSQL(`
      CREATE TABLE users (id SERIAL PRIMARY KEY, email TEXT NOT NULL);
      CREATE TABLE posts (
        id SERIAL PRIMARY KEY,
        user_id INT NOT NULL REFERENCES users (id)
      );
    `);
    const result = compile(dbml);
    expect(result.diagnostics.filter((d) => d.severity === 'error')).toEqual([]);
    expect(result.schema.tables.map((t) => t.name)).toEqual(['users', 'posts']);
    expect(result.schema.refs).toHaveLength(1);
  });
});
