/**
 * DBML → SQL DDL.
 *
 * Supports the two dialects people actually paste into a console: PostgreSQL
 * and MySQL. The differences that matter here are quoting, auto-increment,
 * enum support (native types vs. inline `ENUM(...)`) and where comments go.
 */

import { Column, Enum, Index, Schema, Table } from '../dbml';

export type Dialect = 'postgres' | 'mysql';

export interface ExportOptions {
  dialect: Dialect;
  /** Emit `CREATE SCHEMA` for any non-default schema used. */
  includeSchemas?: boolean;
}

export function toSQL(schema: Schema, options: ExportOptions): string {
  const { dialect } = options;
  const blocks: string[] = [];

  if (schema.project?.name) {
    blocks.push(`-- ${schema.project.name}${
      schema.project.note ? `\n-- ${schema.project.note.replace(/\n/g, '\n-- ')}` : ''
    }`);
  }

  if (options.includeSchemas !== false) {
    const schemas = [...new Set(schema.tables.map((table) => table.schema))].filter(
      (name) => name !== 'public',
    );
    for (const name of schemas) {
      blocks.push(`CREATE SCHEMA IF NOT EXISTS ${quote(name, dialect)};`);
    }
  }

  if (dialect === 'postgres') {
    for (const model of schema.enums) {
      blocks.push(createEnum(model, dialect));
    }
  }

  for (const table of schema.tables) {
    blocks.push(createTable(table, schema, options));
    blocks.push(...createIndexes(table, options));
    if (dialect === 'postgres') blocks.push(...comments(table, dialect));
  }

  for (const ref of schema.refs) {
    const statement = foreignKey(ref, schema, dialect);
    if (statement) blocks.push(statement);
  }

  return `${blocks.filter(Boolean).join('\n\n')}\n`;
}

function createEnum(model: Enum, dialect: Dialect): string {
  const values = model.values.map((value) => `'${escapeString(value.name)}'`).join(', ');
  return `CREATE TYPE ${qualified(model.schema, model.name, dialect)} AS ENUM (${values});`;
}

function createTable(table: Table, schema: Schema, options: ExportOptions): string {
  const { dialect } = options;
  const primaryKeys = table.columns.filter((column) => column.pk);
  const compositeIndexPk = table.indexes.find((index) => index.pk);
  // A lone primary key is inlined; composite keys become a table constraint.
  const inlinePk = primaryKeys.length === 1 && !compositeIndexPk ? primaryKeys[0].id : null;

  const lines: string[] = table.columns.map(
    (column) => `  ${columnDefinition(column, schema, options, column.id === inlinePk)}`,
  );

  if (primaryKeys.length > 1) {
    lines.push(
      `  PRIMARY KEY (${primaryKeys.map((column) => quote(column.name, dialect)).join(', ')})`,
    );
  } else if (compositeIndexPk) {
    lines.push(
      `  PRIMARY KEY (${compositeIndexPk.columns
        .map((column) => indexColumn(column, dialect))
        .join(', ')})`,
    );
  }

  const comment =
    dialect === 'mysql' && table.note ? ` COMMENT = '${escapeString(table.note)}'` : '';
  return `CREATE TABLE ${qualified(table.schema, table.name, dialect)} (\n${lines.join(',\n')}\n)${comment};`;
}

function columnDefinition(
  column: Column,
  schema: Schema,
  options: ExportOptions,
  inlinePrimaryKey: boolean,
): string {
  const { dialect } = options;
  const parts = [quote(column.name, dialect), columnType(column, schema, dialect)];

  if (column.increment) {
    parts.push(dialect === 'mysql' ? 'AUTO_INCREMENT' : 'GENERATED BY DEFAULT AS IDENTITY');
  }
  if (inlinePrimaryKey) parts.push('PRIMARY KEY');
  else if (column.notNull || column.pk) parts.push('NOT NULL');
  if (column.unique && !inlinePrimaryKey) parts.push('UNIQUE');
  if (column.default) parts.push(`DEFAULT ${defaultLiteral(column)}`);
  if (dialect === 'mysql' && column.note) parts.push(`COMMENT '${escapeString(column.note)}'`);

  return parts.join(' ');
}

function columnType(column: Column, schema: Schema, dialect: Dialect): string {
  if (column.enumId) {
    const model = schema.enums.find((candidate) => candidate.id === column.enumId);
    if (model) {
      return dialect === 'postgres'
        ? qualified(model.schema, model.name, dialect)
        : `ENUM(${model.values.map((value) => `'${escapeString(value.name)}'`).join(', ')})`;
    }
  }
  // `serial` already implies auto-increment in Postgres.
  if (dialect === 'mysql' && /^(big)?serial$/i.test(column.typeName)) {
    return /^big/i.test(column.typeName) ? 'BIGINT' : 'INT';
  }
  return column.typeArgs ? `${column.typeName}(${column.typeArgs})` : column.typeName;
}

function defaultLiteral(column: Column): string {
  const value = column.default!;
  switch (value.type) {
    case 'string':
      return `'${escapeString(value.value)}'`;
    case 'expression':
      return `(${value.value})`;
    case 'null':
      return 'NULL';
    default:
      return value.value;
  }
}

function createIndexes(table: Table, options: ExportOptions): string[] {
  const { dialect } = options;
  const statements: string[] = [];
  table.indexes.forEach((index, position) => {
    if (index.pk) return;
    const name = index.name ?? `${table.name}_index_${position}`;
    const columns = index.columns.map((column) => indexColumn(column, dialect)).join(', ');
    const unique = index.unique ? 'UNIQUE ' : '';
    const using = index.type && dialect === 'postgres' ? ` USING ${index.type.toUpperCase()}` : '';
    statements.push(
      `CREATE ${unique}INDEX ${quote(name, dialect)} ON ${qualified(
        table.schema,
        table.name,
        dialect,
      )}${using} (${columns});`,
    );
  });
  return statements;
}

function indexColumn(column: Index['columns'][number], dialect: Dialect): string {
  return column.kind === 'expression' ? `(${column.value})` : quote(column.value, dialect);
}

function comments(table: Table, dialect: Dialect): string[] {
  const statements: string[] = [];
  if (table.note) {
    statements.push(
      `COMMENT ON TABLE ${qualified(table.schema, table.name, dialect)} IS '${escapeString(table.note)}';`,
    );
  }
  for (const column of table.columns) {
    if (!column.note) continue;
    statements.push(
      `COMMENT ON COLUMN ${qualified(table.schema, table.name, dialect)}.${quote(
        column.name,
        dialect,
      )} IS '${escapeString(column.note)}';`,
    );
  }
  return statements;
}

function foreignKey(ref: Schema['refs'][number], schema: Schema, dialect: Dialect): string | null {
  const [left, right] = ref.endpoints;
  // The many-side holds the foreign key; a 1–1 keeps the declared direction.
  const [child, parent] =
    left.relation === '*' && right.relation === '1'
      ? [left, right]
      : right.relation === '*' && left.relation === '1'
        ? [right, left]
        : [left, right];

  if (left.relation === '*' && right.relation === '*') return null; // needs a join table

  const childTable = schema.tables.find((table) => table.id === child.tableId);
  const parentTable = schema.tables.find((table) => table.id === parent.tableId);
  if (!childTable || !parentTable) return null;

  const name = ref.name ?? `fk_${childTable.name}_${child.columnNames.join('_')}`;
  const actions = [
    ref.onDelete ? ` ON DELETE ${ref.onDelete.toUpperCase()}` : '',
    ref.onUpdate ? ` ON UPDATE ${ref.onUpdate.toUpperCase()}` : '',
  ].join('');

  return (
    `ALTER TABLE ${qualified(childTable.schema, childTable.name, dialect)} ` +
    `ADD CONSTRAINT ${quote(name, dialect)} FOREIGN KEY (${child.columnNames
      .map((column) => quote(column, dialect))
      .join(', ')}) ` +
    `REFERENCES ${qualified(parentTable.schema, parentTable.name, dialect)} (${parent.columnNames
      .map((column) => quote(column, dialect))
      .join(', ')})${actions};`
  );
}

function qualified(schemaName: string, name: string, dialect: Dialect): string {
  return schemaName && schemaName !== 'public'
    ? `${quote(schemaName, dialect)}.${quote(name, dialect)}`
    : quote(name, dialect);
}

function quote(identifier: string, dialect: Dialect): string {
  return dialect === 'mysql'
    ? `\`${identifier.replace(/`/g, '``')}\``
    : `"${identifier.replace(/"/g, '""')}"`;
}

function escapeString(value: string): string {
  return value.replace(/'/g, "''");
}
